image:
  name: maven:3.8.5-openjdk-18

stages:
  - package
  - coverage

cache:
  paths:
    - .m2/repository/

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/

coverage:
  dependencies:
    - package
  stage: coverage
  coverage: "/Total.*?([0-9]{1,3})%/"
  script:
    - mvn jacoco:report
    - cat target/site/jacoco/index.html | grep -o '<tfoot>.*</tfoot>'
  artifacts:
    paths:
      - target/surefire-reports
      - target/site/jacoco/jacoco.xml
      - target/jacoco.exec
