version: "3.9"

services:

  server:
    container_name: spring_container_trpp
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres_container_trpp:5432/spring_db"
      SPRING_DATASOURCE_USERNAME: "argoc"
      SPRING_DATASOURCE_PASSWORD: "123"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

  postgres:
    container_name: postgres_container_trpp
    image: postgres:13.3
    environment:
      POSTGRES_DB: "spring_db"
      POSTGRES_USER: "argoc"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U argoc -d spring_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
